@startuml

title A mental model on Google Cloud Data Catalog core entities\n


Catalog <. SearchResult
Catalog <.. Entry
SearchResult .. Entry
SearchResult .. TagTemplate

Entry <|-- ManualEntry
Entry <|-- SynchronizedEntry
Schema -* Entry
Schema *-- ColumnSchema : columns
ColumnSchema *-- ColumnSchema : subcolumns

Tag o- TagTemplate : template
Tag *-- TagField : fields
TagTemplate *-- TagTemplateField : fields
TagTemplateField *-- FieldType : type
FieldType o-- PrimitiveType : primitiveType
FieldType *-- EnumType : enumType

Entry -o Tag : entry

@enduml
