@startuml

!includesub entry-classes.plantuml!MAINCLASSES
!includesub tag-template-tag-classes.plantuml!MAINCLASSES


title A mental model on Google Cloud Data Catalog Entry, Tag & Tag Template relationships\n


Entry -o Tag : entry
Tag o- TagTemplate : template
Tag *-- "1..*" TagField : fields

@enduml
