@startuml

skinparam backgroundcolor transparent


!includesub entry-classes.plantuml!MAINCLASSES
!includesub tag-template-tag-classes.plantuml!MAINCLASSES


title A mental model on Google Cloud Data Catalog Entry, Tag & Tag Template relationships\n


Entry <- Tag : < annotates
Tag -> TagTemplate
Tag *-- "1..*" TagField

@enduml
