@startuml

skinparam backgroundcolor transparent


title A mental model on Google Cloud Data Catalog Search related entities\n


Catalog -> SearchResult


!startsub MAINCLASSES
class Catalog {
  +{static}SearchResult[] search()
  +{static}Entry lookupEntry()
}

class SearchResult {
  -String searchResultType
  -String searchResultSubtype
  -String relativeResourceName
  -String linkedResource
}
!endsub

@enduml
